const randomURL = "https://www.boredapi.com/api/activity";
const typeURL = "http://www.boredapi.com/api/activity?type=";
const partURL1 = "http://www.boredapi.com/api/activity?participants=1";
const partURL2 = "http://www.boredapi.com/api/activity?participants=2";
const partURL3 = "http://www.boredapi.com/api/activity?participants=3";
const partURL4 = "http://www.boredapi.com/api/activity?participants=4";
const partURL5 = "http://www.boredapi.com/api/activity?participants=5";

export { randomURL, typeURL, partURL1, partURL2, partURL3, partURL4, partURL5 };
